name: update-nix
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 5 * * *" # 5 am UTC

permissions:
  pull-requests: write
  actions: write


jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependacies
          pr-reviewers: eveeifyeve
          token: ${{secrets.GITHUB_TOKEN}}
