name: update-nix
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # 5 am UTC

permissions: write-all

env:
  #TODO: On pr to main please change this.
  OUT_BRANCH: "feat/improve-conf"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Create Branch
        run: echo "BRANCH_NAME=update-nix-$(date +'%Y-%m-%d')" >> $GITHUB_ENV 
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30

      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git branch ${{ env.BRANCH_NAME }}
          git checkout ${{ env.BRNACH_NAME }}

      - name: Update Flake 
        shell: bash
        run: nix flake update 

      - name: Commit 
        run: |
          git add . 
          git commit -m "chore: updated flake"
          git push
      
      - name: Get PR Body
        run: echo "PR_BODY=$(cat .github/UPDATE_NIX_BODY.txt)" >> $GITHUB_ENV

      - name: Make a PR
        run: gh pr create -B ${{env.BRANCH_NAME}} -H ${{env.OUT_BRANCH}} --title "Update flake lock" --body ${{env.PR_BODY}} 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
