name: update-nix
on:
  schedule:
    - cron: '0 5 * * *' # run at 5 AM UTC
  workflow_dispatch:

permissions: write-all

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30

      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update Flake 
        shell: bash
        run: 'nix flake update --commit-lock-file --option --commit-lockfile-summary "chore: updated flake lock"' 
